packages:
  - 'apps/*'
  - 'backend/*'
  - 'packages/*'
  - 'database/*'
  - 'pv-core'

allowBuilds:
  esbuild: set this to true or false

onlyBuiltDependencies:
  - esbuild
  - sharp

settings:
  lockfileVersion: v9
  autoInstallPeers: true
